-- ALTER TABLE (ADD, ALTER, DROP)

-- ADICIONAR UMA NOVA COLUNA A TABELA EXISTENTE
ALTER TABLE LIVRO
ADD EDICAO SMALLINT;

-- ALTERAR O TIPO DE DADO DE UMA COLUNA EXISTENTE
ALTER TABLE LIVRO
ALTER COLUMN EDICAO TINYINT;

-- ADICIONAR CHAVE PRIMARIA CASO NÃO EXISTA
ALTER TABLE LIVRO
ADD PRIMARY KEY (nome_coluna);

-- EXCLUIR UMA CONSTRAINT DE UMA COLUNA
-- VERIFICAR O NOME DA CONSTRAINT ANTES DE EXECUTAR ESTE COMANDO
SP_HELP LIVRO;
ALTER TABLE LIVRO
DROP CONSTRAINT nome_constraint;

-- EXCLUIR UMA COLUNA DA TABELA
ALTER TABLE LIVRO
DROP COLUMN EDICAO;

-- EXCLUIR TABELA
DROP TABLE LIVRO;

