--CRIANDO DATABASE COM DEFINI��ES PADROES 
CREATE DATABASE ESTUDOS_02;

-- CRIANDO DB COM SINTAXE EXTENDIDA
CREATE DATABASE ESTUDOS_02 ON PRIMARY -- ON PRIMARY PRA SE REFERIR A QUAL INSTANCIA SERA CRIADO
(	NAME = ESTUDOS,
	FILENAME = 'C:\SQL\ESTUDOS.mdf', -- NOME DO ARQUIVO FISICO, ONDE SER� SALVO
	SIZE = 6MB,
	FILEGROWTH = 10% -- DE QNTO EM QNTO IR� CRESCER
)
LOG ON -- ONDE FICA REGISTRADO AS TRANSA��ES DO DB
(	NAME = ESTUDOS_LOG,
	FILENAME = 'C:\SQL\ESTUDOS.ldf',
	FILEGROWTH = 1%
)
GO -- O GO EXECUTA EM LOTE TODOS OS COMANDOS E SE HOUVER FALHA ELES N�O SER�O EXECUTADOS

-- CONSULTAR OS DB EXISTENTES
SELECT NAME FROM MASTER.SYS.DATABASES
ORDER BY NAME;

EXEC sp_databases;

-- SELECIONAR O BANCO PARA USAR
-- USE ESTUDOS_02;

SELECT 2*2;

-- PRA TRAZER INFORMACOES ESPECIFICAS DE ALGUM DB
EXEC sp_helpdb ESTUDOS;

-- PARA EXCLUIR DB COM DROP (O DB N�O PODE ESTAR EM USO AO TENTAR EXCLUIR)
DROP DATABASE IF EXISTS ESTUDOS_02;

-- PARA EXCLUIR BANCO EM USO
USE MASTER
GO
ALTER DATABASE ESTUDOS SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
-- DROP DATABASE ESTUDOS_02;

-- USE ESTUDOS_02; -- CONFERINDO SE FOI ESCLUIDO